import {test,expect} from '@playwright/test';
async function login(page){await page.goto('/');await page.getByLabel('E-mail',{exact:true}).fill('portfolio@example.com');await page.getByLabel('Senha',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.locator('.stats')).toBeVisible();}
test('fluxo completo: login, categoria, produto, movimentos, filtros, alertas e logout',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page);
 await page.locator('[data-page="categories"]').click();await page.getByRole('button',{name:'Nova categoria'}).click();await page.getByLabel('Nome da categoria').fill('Categoria de teste');await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page.getByRole('heading',{name:'Categoria de teste',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Novo produto'}).click();await page.getByLabel('Nome do produto').fill('Produto de teste');await page.getByLabel('SKU / código').fill('TEST-001');await page.getByRole('combobox',{name:'Categoria',exact:true}).selectOption({label:'Categoria de teste'});await page.getByLabel('Preço unitário').fill('19.90');await page.getByLabel('Estoque mínimo').fill('5');await page.getByRole('button',{name:'Salvar',exact:true}).click();await expect(page.locator('#modal')).not.toBeVisible();
 await page.locator('[data-page="products"]').click();await page.getByRole('searchbox').fill('TEST-001');await expect(page.getByRole('cell',{name:'Produto de teste TEST-001'})).toBeVisible();await expect(page.locator('tbody .badge.zero')).toBeVisible();
 async function movement(type,quantity){await page.getByRole('button',{name:'Registrar movimento',exact:false}).first().click();const id=await page.locator('select[name=product_id] option').evaluateAll(options=>options.find(o=>o.textContent.includes('TEST-001')).value);await page.getByRole('combobox',{name:'Produto',exact:true}).selectOption(id);await page.getByRole('combobox',{name:'Tipo',exact:true}).selectOption(type);await page.getByLabel('Quantidade (un.)').fill(String(quantity));await page.getByLabel('Motivo').fill('Teste de movimento');await page.locator('#save-modal').click();}
 await movement('IN',10);await expect(page.locator('#modal')).not.toBeVisible();await expect(page.locator('tbody .badge.good')).toBeVisible();
 await movement('OUT',11);await expect(page.locator('#modal-error')).toHaveText('Saldo insuficiente para esta saída.');await page.getByLabel('Quantidade (un.)').fill('6');await page.locator('#save-modal').click();await expect(page.locator('#modal')).not.toBeVisible();await expect(page.locator('tbody .badge.low')).toBeVisible();
 await page.getByRole('button',{name:'Editar Produto de teste'}).click();await page.getByLabel('Nome do produto').fill('Produto revisado');await page.locator('#save-modal').click();await expect(page.locator('#modal')).not.toBeVisible();await expect(page.getByRole('cell',{name:'Produto revisado TEST-001'})).toBeVisible();
 await page.locator('[data-page="movements"]').click();await page.getByRole('searchbox').fill('TEST-001');await expect(page.locator('tbody tr')).toHaveCount(2);await page.getByLabel('Tipo de movimento').selectOption('OUT');await expect(page.locator('tbody tr')).toHaveCount(1);
 await page.locator('[data-page="products"]').click();await page.getByRole('searchbox').fill('TEST-001');await page.getByRole('button',{name:'Excluir Produto revisado'}).click();await page.locator('#save-modal').click();await expect(page.locator('#modal-error')).toContainText('Zere o estoque');await page.getByRole('button',{name:'Cancelar',exact:true}).click();
 await movement('OUT',4);await expect(page.locator('#modal')).not.toBeVisible();await page.getByRole('button',{name:'Excluir Produto revisado'}).click();await page.locator('#save-modal').click();await expect(page.locator('#modal')).not.toBeVisible();await expect(page.getByText('Nenhum produto encontrado')).toBeVisible();
 await page.locator('[data-page="movements"]').click();await page.getByRole('searchbox').fill('TEST-001');await expect(page.locator('tbody tr')).toHaveCount(3);
 await page.locator('[data-page="categories"]').click();const card=page.locator('.category-card').filter({hasText:'Categoria de teste'});await card.getByRole('button',{name:'Excluir',exact:true}).click();await page.locator('#save-modal').click();await expect(card).toHaveCount(0);
 await page.getByRole('button',{name:'Sair da conta'}).click();await expect(page.locator('#login-screen')).toBeVisible();await expect(page.locator('#app')).not.toBeVisible();expect(errors).toEqual([]);
});
test('interface responsiva, conteúdo escapado e capturas para portfólio',async({page})=>{
 await page.setViewportSize({width:1440,height:1024});await page.goto('/');await page.screenshot({path:'docs/login.png',fullPage:true});await login(page);
 await page.screenshot({path:'docs/dashboard.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await expect(page.locator('.stats')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'docs/mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Novo produto'}).click();await page.getByLabel('Nome do produto').fill('<img src=x onerror=alert(1)>');await page.getByLabel('SKU / código').fill('XSS-CHECK');await page.getByLabel('Preço unitário').fill('1');await page.locator('#save-modal').click();await expect(page.locator('#modal')).not.toBeVisible();await page.locator('[data-page="products"]').click();await page.getByRole('searchbox').fill('XSS-CHECK');await expect(page.getByText('<img src=x onerror=alert(1)>',{exact:true})).toBeVisible();await expect(page.locator('tbody img')).toHaveCount(0);
});
